service: hedgehog-learn
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:AWS_REGION, 'us-east-1'}
  stage: ${env:APP_STAGE, 'dev'}
  environment:
    HUBSPOT_PROJECT_ACCESS_TOKEN: ${env:HUBSPOT_PROJECT_ACCESS_TOKEN, ''}
    HUBSPOT_PRIVATE_APP_TOKEN: ${env:HUBSPOT_PRIVATE_APP_TOKEN}
    HUBSPOT_ACCOUNT_ID: ${env:HUBSPOT_ACCOUNT_ID}
    ENABLE_CRM_PROGRESS: ${env:ENABLE_CRM_PROGRESS, 'false'}
    PROGRESS_BACKEND: ${env:PROGRESS_BACKEND, 'properties'}
  httpApi:
    cors: true

functions:
  api:
    handler: dist/src/api/lambda/index.handler
    events:
      - httpApi:
          path: /events/track
          method: POST
      - httpApi:
          path: /quiz/grade
          method: POST
      - httpApi:
          path: /progress/read
          method: GET

package:
  individually: true
  patterns:
    # Include only compiled lambda code
    - 'dist/src/api/**'
    - 'dist/src/shared/**'
    # Include only the minimal runtime dependencies used by the lambda
    - 'node_modules/@hubspot/api-client/**'
    - 'node_modules/bottleneck/**'
    - 'node_modules/es6-promise/**'
    - 'node_modules/form-data/**'
    - 'node_modules/lodash.get/**'
    - 'node_modules/lodash.merge/**'
    - 'node_modules/node-fetch/**'
    - 'node_modules/url-parse/**'
    - 'node_modules/zod/**'
    # Exclude everything else by default
    - '!**/*.test.*'
    - '!**/*.spec.*'
    - '!**/*.map'
    - '!**/*.ts'
    - '!**/*.md'
    - '!tests/**'
    - '!infra/**'
    - '!docs/**'
    - '!reference/**'
    - '!hubdb-schemas/**'
    - '!src/**'
    - '!content/**'
    - '!scripts/**'
    - '!clean-x-hedgehog-templates/**'
    - '!verification-output/**'
    - '!aws/**'
    - '!*.zip'
    - '!.git/**'
    - '!.github/**'
    - '!.serverless/**'
    - '!.serverless-artifacts/**'
    - '!.playwright/**'
    - '!playwright-report/**'
    - '!test-results/**'
    - '!node_modules/@types/**'
    - '!node_modules/aws-sdk/**'  # Provided by Lambda
    - '!package-lock.json'
    - '!.env'
    - '!.env.*'
    - '!.eslintrc.*'
    - '!.prettierrc*'
    - '!.hsignore'
    - '!*.yml'
    - '!*.yaml'
    - '!*.json'
    - '!*.html'
    - '!*.csv'
    - '!dist/scripts/**'
    - '!dist/src/sync/**'
