name: Auto Code Review (Codex)

on:
  pull_request_target:
    types: [opened, reopened, ready_for_review]

permissions:
  pull-requests: write
  issues: write

jobs:
  request-review:
    runs-on: ubuntu-latest
    steps:
      - name: Comment to trigger Codex code review
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) return core.setFailed('No PR payload');
            const body = '@codex review\n\nAutomated trigger: requesting an independent code review for this PR.';
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body,
            });
